# Generated by Django 2.2.1 on 2020-07-27 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200726_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywishlist',
            name='items',
            field=models.ManyToManyField(to='product.Items'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivary_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 12, 42, 46, 937634)),
        ),
    ]
