# Generated by Django 2.2.1 on 2020-07-13 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200712_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivary_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 12, 10, 40, 15, 415477)),
        ),
    ]
