# Generated by Django 2.2.1 on 2020-07-29 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200727_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivary_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 5, 20, 2, 57, 457977)),
        ),
    ]
