# Generated by Django 2.2.1 on 2020-07-13 05:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_order_delivary_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivary_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 20, 10, 46, 22, 330808)),
        ),
    ]
