# Generated by Django 2.2.2 on 2020-07-13 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200713_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivary_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 20, 22, 41, 49, 948597)),
        ),
    ]
