# Generated by Django 2.2.1 on 2020-07-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200705_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='desc',
            new_name='description',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='category/'),
        ),
        migrations.AddField(
            model_name='product',
            name='information',
            field=models.TextField(default='This is the best product'),
            preserve_default=False,
        ),
    ]
