# Generated by Django 2.2.1 on 2020-07-25 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20200722_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivary_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 13, 40, 24, 425610)),
        ),
    ]
